<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'login',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:57',
                'parent_id' => 45,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'logout',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'register',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'password.request',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'password.email',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'password.reset',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'password.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 06:16:58',
                'parent_id' => 45,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'home',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2020-03-20 05:07:23',
                'parent_id' => 0,
                'order' => 31,
                'icon' => NULL,
                'isURL' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'role.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 9,
                'icon' => NULL,
                'isURL' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'role.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 10,
                'icon' => NULL,
                'isURL' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'role.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 11,
                'icon' => NULL,
                'isURL' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'role.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 12,
                'icon' => NULL,
                'isURL' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'role.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 13,
                'icon' => NULL,
                'isURL' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'role.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 14,
                'icon' => NULL,
                'isURL' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'role.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 9,
                'order' => 15,
                'icon' => NULL,
                'isURL' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'permission.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:35',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 16,
                'icon' => NULL,
                'isURL' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'permission.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 17,
                'icon' => NULL,
                'isURL' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'permission.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 18,
                'icon' => NULL,
                'isURL' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'permission.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 19,
                'icon' => NULL,
                'isURL' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'permission.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 20,
                'icon' => NULL,
                'isURL' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'permission.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 21,
                'icon' => NULL,
                'isURL' => 1,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'permission.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 22,
                'icon' => NULL,
                'isURL' => 1,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'permission.add',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 23,
                'icon' => NULL,
                'isURL' => 1,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'permission.addmenu',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 16,
                'order' => 24,
                'icon' => NULL,
                'isURL' => 1,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'user.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 25,
                'icon' => NULL,
                'isURL' => 1,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'user.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 26,
                'icon' => NULL,
                'isURL' => 1,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'user.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 27,
                'icon' => NULL,
                'isURL' => 1,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'user.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 28,
                'icon' => NULL,
                'isURL' => 1,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'user.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 29,
                'icon' => NULL,
                'isURL' => 1,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'user.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 30,
                'icon' => NULL,
                'isURL' => 1,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'user.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 25,
                'order' => 31,
                'icon' => NULL,
                'isURL' => 1,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'assignrole.index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 8,
                'order' => 32,
                'icon' => NULL,
                'isURL' => 1,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'assignrole.create',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 33,
                'icon' => NULL,
                'isURL' => 1,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'assignrole.store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 34,
                'icon' => NULL,
                'isURL' => 1,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'assignrole.show',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 35,
                'icon' => NULL,
                'isURL' => 1,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'assignrole.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 36,
                'icon' => NULL,
                'isURL' => 1,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'assignrole.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 37,
                'icon' => NULL,
                'isURL' => 1,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'assignrole.destroy',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:12:36',
                'updated_at' => '2019-01-02 10:06:05',
                'parent_id' => 32,
                'order' => 38,
                'icon' => NULL,
                'isURL' => 1,
            ),
            38 => 
            array (
                'id' => 45,
                'name' => '#always',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 06:14:01',
                'updated_at' => '2020-03-20 05:07:23',
                'parent_id' => 0,
                'order' => 30,
                'icon' => NULL,
                'isURL' => 0,
            ),
            39 => 
            array (
                'id' => 46,
                'name' => '#usermanagement',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 09:25:56',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 8,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 0,
            ),
            40 => 
            array (
                'id' => 47,
                'name' => 'menu-index',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 46,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            41 => 
            array (
                'id' => 48,
                'name' => 'menu-store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 46,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            42 => 
            array (
                'id' => 49,
                'name' => 'menu-build-menu',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:03',
                'parent_id' => 46,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            43 => 
            array (
                'id' => 50,
                'name' => 'menu-delete',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 46,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            44 => 
            array (
                'id' => 51,
                'name' => 'menu-search',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 46,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            45 => 
            array (
                'id' => 52,
                'name' => 'display-name-store',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-01-02 10:05:27',
                'updated_at' => '2019-01-02 10:06:04',
                'parent_id' => 46,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
            46 => 
            array (
                'id' => 53,
                'name' => 'brand.index',
                'display_name' => 'Index',
                'description' => NULL,
                'created_at' => '2019-10-24 08:43:28',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 27,
                'icon' => NULL,
                'isURL' => 1,
            ),
            47 => 
            array (
                'id' => 54,
                'name' => 'brand.create',
                'display_name' => 'Create',
                'description' => NULL,
                'created_at' => '2019-10-24 08:43:28',
                'updated_at' => '2019-10-24 08:44:02',
                'parent_id' => 53,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            48 => 
            array (
                'id' => 55,
                'name' => 'brand.store',
                'display_name' => 'Store',
                'description' => NULL,
                'created_at' => '2019-10-24 08:43:28',
                'updated_at' => '2019-10-24 08:44:02',
                'parent_id' => 53,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            49 => 
            array (
                'id' => 56,
                'name' => 'brand.show',
                'display_name' => 'Show',
                'description' => NULL,
                'created_at' => '2019-10-24 08:43:28',
                'updated_at' => '2019-10-24 08:44:02',
                'parent_id' => 53,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            50 => 
            array (
                'id' => 57,
                'name' => 'brand.edit',
                'display_name' => 'Edit',
                'description' => NULL,
                'created_at' => '2019-10-24 08:43:28',
                'updated_at' => '2019-10-24 08:44:02',
                'parent_id' => 53,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            51 => 
            array (
                'id' => 58,
                'name' => 'brand.update',
                'display_name' => 'Update',
                'description' => NULL,
                'created_at' => '2019-10-24 08:43:28',
                'updated_at' => '2019-10-24 08:44:02',
                'parent_id' => 53,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            52 => 
            array (
                'id' => 59,
                'name' => 'brand.destroy',
                'display_name' => 'Destroy',
                'description' => NULL,
                'created_at' => '2019-10-24 08:43:29',
                'updated_at' => '2019-10-24 08:44:03',
                'parent_id' => 53,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            53 => 
            array (
                'id' => 60,
                'name' => 'user-password.edit',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-10-24 08:43:29',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 28,
                'icon' => NULL,
                'isURL' => 1,
            ),
            54 => 
            array (
                'id' => 61,
                'name' => 'user-password.update',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-10-24 08:43:29',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 29,
                'icon' => NULL,
                'isURL' => 1,
            ),
            55 => 
            array (
                'id' => 62,
                'name' => 'model.index',
                'display_name' => 'Index',
                'description' => NULL,
                'created_at' => '2019-10-24 09:04:29',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 26,
                'icon' => NULL,
                'isURL' => 1,
            ),
            56 => 
            array (
                'id' => 63,
                'name' => 'model.create',
                'display_name' => 'Create',
                'description' => NULL,
                'created_at' => '2019-10-24 09:04:29',
                'updated_at' => '2019-10-24 09:04:58',
                'parent_id' => 62,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            57 => 
            array (
                'id' => 64,
                'name' => 'model.store',
                'display_name' => 'Store',
                'description' => NULL,
                'created_at' => '2019-10-24 09:04:29',
                'updated_at' => '2019-10-24 09:04:58',
                'parent_id' => 62,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            58 => 
            array (
                'id' => 65,
                'name' => 'model.show',
                'display_name' => 'Show',
                'description' => NULL,
                'created_at' => '2019-10-24 09:04:29',
                'updated_at' => '2019-10-24 09:04:58',
                'parent_id' => 62,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            59 => 
            array (
                'id' => 66,
                'name' => 'model.edit',
                'display_name' => 'Edit',
                'description' => NULL,
                'created_at' => '2019-10-24 09:04:29',
                'updated_at' => '2019-10-24 09:04:58',
                'parent_id' => 62,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            60 => 
            array (
                'id' => 67,
                'name' => 'model.update',
                'display_name' => 'Update',
                'description' => NULL,
                'created_at' => '2019-10-24 09:04:29',
                'updated_at' => '2019-10-24 09:04:59',
                'parent_id' => 62,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            61 => 
            array (
                'id' => 68,
                'name' => 'model.destroy',
                'display_name' => 'Destroy',
                'description' => NULL,
                'created_at' => '2019-10-24 09:04:29',
                'updated_at' => '2019-10-24 09:04:59',
                'parent_id' => 62,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            62 => 
            array (
                'id' => 69,
                'name' => 'model.variantdetails',
                'display_name' => 'Variant Details',
                'description' => NULL,
                'created_at' => '2019-11-03 04:50:12',
                'updated_at' => '2019-11-03 04:50:29',
                'parent_id' => 62,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
            63 => 
            array (
                'id' => 73,
                'name' => '#Settings',
                'display_name' => 'Settings',
                'description' => NULL,
                'created_at' => '2019-11-03 06:30:48',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 25,
                'icon' => NULL,
                'isURL' => 0,
            ),
            64 => 
            array (
                'id' => 96,
                'name' => 'debugbar.openhandler',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-11-06 05:02:53',
                'updated_at' => '2020-03-20 05:07:23',
                'parent_id' => 0,
                'order' => 32,
                'icon' => NULL,
                'isURL' => 1,
            ),
            65 => 
            array (
                'id' => 97,
                'name' => 'debugbar.clockwork',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-11-06 05:02:54',
                'updated_at' => '2019-11-06 05:05:31',
                'parent_id' => 96,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            66 => 
            array (
                'id' => 98,
                'name' => 'debugbar.telescope',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-11-06 05:02:54',
                'updated_at' => '2019-11-06 05:05:31',
                'parent_id' => 96,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            67 => 
            array (
                'id' => 99,
                'name' => 'debugbar.assets.css',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-11-06 05:02:54',
                'updated_at' => '2019-11-06 05:05:31',
                'parent_id' => 96,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            68 => 
            array (
                'id' => 100,
                'name' => 'debugbar.assets.js',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-11-06 05:02:54',
                'updated_at' => '2019-11-06 05:05:31',
                'parent_id' => 96,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            69 => 
            array (
                'id' => 101,
                'name' => 'debugbar.cache.delete',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-11-06 05:02:54',
                'updated_at' => '2019-11-06 05:05:31',
                'parent_id' => 96,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            70 => 
            array (
                'id' => 102,
                'name' => 'specs.create',
                'display_name' => 'Create',
                'description' => NULL,
                'created_at' => '2019-11-06 05:02:54',
                'updated_at' => '2019-11-06 05:05:31',
                'parent_id' => 104,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            71 => 
            array (
                'id' => 103,
                'name' => 'specs.store',
                'display_name' => 'Store',
                'description' => NULL,
                'created_at' => '2019-11-06 05:02:54',
                'updated_at' => '2019-11-06 05:05:31',
                'parent_id' => 104,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            72 => 
            array (
                'id' => 104,
                'name' => 'specs.index',
                'display_name' => 'Index',
                'description' => NULL,
                'created_at' => '2019-11-06 05:04:24',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 24,
                'icon' => NULL,
                'isURL' => 1,
            ),
            73 => 
            array (
                'id' => 105,
                'name' => 'features.index',
                'display_name' => 'Index',
                'description' => NULL,
                'created_at' => '2019-11-06 05:42:16',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 23,
                'icon' => NULL,
                'isURL' => 1,
            ),
            74 => 
            array (
                'id' => 106,
                'name' => 'features.create',
                'display_name' => 'Create',
                'description' => NULL,
                'created_at' => '2019-11-06 05:42:16',
                'updated_at' => '2019-11-06 05:42:30',
                'parent_id' => 105,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            75 => 
            array (
                'id' => 107,
                'name' => 'features.store',
                'display_name' => 'Store',
                'description' => NULL,
                'created_at' => '2019-11-06 05:42:17',
                'updated_at' => '2019-11-06 05:42:30',
                'parent_id' => 105,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            76 => 
            array (
                'id' => 108,
                'name' => 'details.index',
                'display_name' => 'Index',
                'description' => NULL,
                'created_at' => '2019-11-06 07:06:53',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 22,
                'icon' => NULL,
                'isURL' => 1,
            ),
            77 => 
            array (
                'id' => 109,
                'name' => 'details.create',
                'display_name' => 'Create',
                'description' => NULL,
                'created_at' => '2019-11-06 07:06:53',
                'updated_at' => '2019-11-06 07:07:09',
                'parent_id' => 108,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            78 => 
            array (
                'id' => 110,
                'name' => 'details.store',
                'display_name' => 'Store',
                'description' => NULL,
                'created_at' => '2019-11-06 07:06:53',
                'updated_at' => '2019-11-06 07:07:10',
                'parent_id' => 108,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            79 => 
            array (
                'id' => 123,
                'name' => 'frontend',
                'display_name' => 'Frontend',
                'description' => NULL,
                'created_at' => '2019-12-02 06:07:22',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 18,
                'icon' => NULL,
                'isURL' => 1,
            ),
            80 => 
            array (
                'id' => 124,
                'name' => 'model.compare',
                'display_name' => 'Compare',
                'description' => NULL,
                'created_at' => '2019-12-02 06:07:23',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 19,
                'icon' => NULL,
                'isURL' => 1,
            ),
            81 => 
            array (
                'id' => 125,
                'name' => 'blogs.index',
                'display_name' => 'Index',
                'description' => NULL,
                'created_at' => '2019-12-02 06:07:23',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 21,
                'icon' => NULL,
                'isURL' => 1,
            ),
            82 => 
            array (
                'id' => 126,
                'name' => 'blogs.create',
                'display_name' => 'Create',
                'description' => NULL,
                'created_at' => '2019-12-02 06:07:23',
                'updated_at' => '2019-12-02 06:10:35',
                'parent_id' => 125,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            83 => 
            array (
                'id' => 127,
                'name' => 'blogs.store',
                'display_name' => 'Store',
                'description' => NULL,
                'created_at' => '2019-12-02 06:07:24',
                'updated_at' => '2019-12-02 06:10:35',
                'parent_id' => 125,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            84 => 
            array (
                'id' => 128,
                'name' => 'blog-detail',
                'display_name' => 'Detail',
                'description' => NULL,
                'created_at' => '2019-12-02 06:07:24',
                'updated_at' => '2019-12-02 06:10:35',
                'parent_id' => 125,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            85 => 
            array (
                'id' => 129,
                'name' => 'blogs.destroy',
                'display_name' => 'Destroy',
                'description' => NULL,
                'created_at' => '2019-12-02 06:07:24',
                'updated_at' => '2019-12-02 06:10:35',
                'parent_id' => 125,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            86 => 
            array (
                'id' => 130,
                'name' => 'frontend.brandpage',
                'display_name' => 'Brand Page',
                'description' => NULL,
                'created_at' => '2019-12-02 06:07:24',
                'updated_at' => '2019-12-02 06:10:34',
                'parent_id' => 123,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            87 => 
            array (
                'id' => 131,
                'name' => 'frontend.modeldetail',
                'display_name' => 'Model Detail',
                'description' => NULL,
                'created_at' => '2019-12-02 06:07:24',
                'updated_at' => '2019-12-02 06:10:34',
                'parent_id' => 123,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            88 => 
            array (
                'id' => 132,
                'name' => 'review.create',
                'display_name' => 'Create',
                'description' => NULL,
                'created_at' => '2019-12-03 05:22:00',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 17,
                'icon' => NULL,
                'isURL' => 1,
            ),
            89 => 
            array (
                'id' => 133,
                'name' => 'review.store',
                'display_name' => 'Store',
                'description' => NULL,
                'created_at' => '2019-12-03 05:22:00',
                'updated_at' => '2019-12-03 05:22:16',
                'parent_id' => 132,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            90 => 
            array (
                'id' => 134,
                'name' => '/',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2019-12-31 04:42:36',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 15,
                'icon' => NULL,
                'isURL' => 1,
            ),
            91 => 
            array (
                'id' => 135,
                'name' => 'category.index',
                'display_name' => 'Index',
                'description' => NULL,
                'created_at' => '2019-12-31 04:42:37',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 16,
                'icon' => NULL,
                'isURL' => 1,
            ),
            92 => 
            array (
                'id' => 136,
                'name' => 'category.store',
                'display_name' => 'Store',
                'description' => NULL,
                'created_at' => '2019-12-31 04:42:37',
                'updated_at' => '2019-12-31 04:47:34',
                'parent_id' => 135,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            93 => 
            array (
                'id' => 137,
                'name' => 'category.create',
                'display_name' => 'Create',
                'description' => NULL,
                'created_at' => '2019-12-31 04:47:23',
                'updated_at' => '2019-12-31 04:47:35',
                'parent_id' => 135,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            94 => 
            array (
                'id' => 140,
                'name' => 'frontend.variantdetail',
                'display_name' => 'Variant Detail',
                'description' => NULL,
                'created_at' => '2020-01-03 10:02:38',
                'updated_at' => '2020-01-03 10:11:13',
                'parent_id' => 123,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            95 => 
            array (
                'id' => 141,
                'name' => 'frontend.search',
                'display_name' => 'Search Model',
                'description' => NULL,
                'created_at' => '2020-01-05 05:30:03',
                'updated_at' => '2020-01-05 05:30:19',
                'parent_id' => 123,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            96 => 
            array (
                'id' => 143,
                'name' => 'get-model',
                'display_name' => 'Get Model',
                'description' => NULL,
                'created_at' => '2020-01-05 06:48:58',
                'updated_at' => '2020-01-05 06:49:10',
                'parent_id' => 123,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            97 => 
            array (
                'id' => 144,
                'name' => 'all-reviews',
                'display_name' => 'All reviews',
                'description' => NULL,
                'created_at' => '2020-01-06 07:03:23',
                'updated_at' => '2020-01-06 07:04:30',
                'parent_id' => 123,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
            98 => 
            array (
                'id' => 145,
                'name' => 'blog-details',
                'display_name' => 'Blog Details',
                'description' => NULL,
                'created_at' => '2020-01-06 07:04:11',
                'updated_at' => '2020-01-06 07:04:31',
                'parent_id' => 123,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            99 => 
            array (
                'id' => 146,
                'name' => 'send-mail',
                'display_name' => 'Mail',
                'description' => NULL,
                'created_at' => '2020-01-09 06:13:39',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 14,
                'icon' => NULL,
                'isURL' => 1,
            ),
            100 => 
            array (
                'id' => 147,
                'name' => 'posts.index',
                'display_name' => 'Index',
                'description' => NULL,
                'created_at' => '2020-01-14 06:27:31',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 13,
                'icon' => NULL,
                'isURL' => 1,
            ),
            101 => 
            array (
                'id' => 148,
                'name' => 'posts.create',
                'display_name' => 'Create',
                'description' => NULL,
                'created_at' => '2020-01-14 06:27:31',
                'updated_at' => '2020-01-14 06:27:55',
                'parent_id' => 147,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            102 => 
            array (
                'id' => 149,
                'name' => 'posts.store',
                'display_name' => 'Store',
                'description' => NULL,
                'created_at' => '2020-01-14 06:27:31',
                'updated_at' => '2020-01-14 06:27:55',
                'parent_id' => 147,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            103 => 
            array (
                'id' => 150,
                'name' => 'post-category.index',
                'display_name' => 'Index',
                'description' => NULL,
                'created_at' => '2020-01-15 06:40:04',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 12,
                'icon' => NULL,
                'isURL' => 1,
            ),
            104 => 
            array (
                'id' => 151,
                'name' => 'post-category.create',
                'display_name' => 'Create',
                'description' => NULL,
                'created_at' => '2020-01-15 06:40:04',
                'updated_at' => '2020-01-15 06:40:32',
                'parent_id' => 150,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            105 => 
            array (
                'id' => 152,
                'name' => 'post-category.store',
                'display_name' => 'Store',
                'description' => NULL,
                'created_at' => '2020-01-15 06:40:04',
                'updated_at' => '2020-01-15 06:40:33',
                'parent_id' => 150,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            106 => 
            array (
                'id' => 153,
                'name' => 'posts.edit',
                'display_name' => 'Edit',
                'description' => NULL,
                'created_at' => '2020-01-16 04:30:27',
                'updated_at' => '2020-01-16 04:31:36',
                'parent_id' => 147,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            107 => 
            array (
                'id' => 154,
                'name' => 'posts.update',
                'display_name' => 'Update',
                'description' => NULL,
                'created_at' => '2020-01-16 04:30:27',
                'updated_at' => '2020-01-16 04:31:36',
                'parent_id' => 147,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            108 => 
            array (
                'id' => 155,
                'name' => 'page',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2020-01-16 04:30:27',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 11,
                'icon' => NULL,
                'isURL' => 1,
            ),
            109 => 
            array (
                'id' => 156,
                'name' => 'ajax-get-models-by-brand-id',
                'display_name' => 'Ajax get models',
                'description' => NULL,
                'created_at' => '2020-02-06 06:21:41',
                'updated_at' => '2020-02-06 06:22:20',
                'parent_id' => 62,
                'order' => 9,
                'icon' => NULL,
                'isURL' => 1,
            ),
            110 => 
            array (
                'id' => 157,
                'name' => 'frontend.compare',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2020-02-06 06:21:42',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 10,
                'icon' => NULL,
                'isURL' => 1,
            ),
            111 => 
            array (
                'id' => 158,
                'name' => 'post-category.edit',
                'display_name' => 'Edit',
                'description' => NULL,
                'created_at' => '2020-02-14 08:15:06',
                'updated_at' => '2020-02-14 08:17:08',
                'parent_id' => 150,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            112 => 
            array (
                'id' => 159,
                'name' => 'post-category.update',
                'display_name' => 'Update',
                'description' => NULL,
                'created_at' => '2020-02-14 08:15:06',
                'updated_at' => '2020-02-14 08:17:09',
                'parent_id' => 150,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            113 => 
            array (
                'id' => 160,
                'name' => 'post-category.destroy',
                'display_name' => 'Destroy',
                'description' => NULL,
                'created_at' => '2020-02-14 08:15:06',
                'updated_at' => '2020-02-14 08:17:10',
                'parent_id' => 150,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            114 => 
            array (
                'id' => 161,
                'name' => 'compareByAjax',
                'display_name' => 'Ajax Comparison',
                'description' => NULL,
                'created_at' => '2020-02-14 09:57:09',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 20,
                'icon' => NULL,
                'isURL' => 1,
            ),
            115 => 
            array (
                'id' => 162,
                'name' => 'category.edit',
                'display_name' => 'Edit',
                'description' => NULL,
                'created_at' => '2020-02-17 04:46:58',
                'updated_at' => '2020-02-17 04:47:57',
                'parent_id' => 135,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            116 => 
            array (
                'id' => 163,
                'name' => 'category.update',
                'display_name' => 'Update',
                'description' => NULL,
                'created_at' => '2020-02-17 04:46:59',
                'updated_at' => '2020-02-17 04:47:57',
                'parent_id' => 135,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            117 => 
            array (
                'id' => 164,
                'name' => 'category.destroy',
                'display_name' => 'Destroy',
                'description' => NULL,
                'created_at' => '2020-02-17 04:46:59',
                'updated_at' => '2020-02-17 04:47:57',
                'parent_id' => 135,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            118 => 
            array (
                'id' => 165,
                'name' => 'specs.destroy',
                'display_name' => 'Destroy',
                'description' => NULL,
                'created_at' => '2020-02-17 05:05:29',
                'updated_at' => '2020-02-17 05:05:48',
                'parent_id' => 104,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            119 => 
            array (
                'id' => 166,
                'name' => 'posts.destroy',
                'display_name' => 'Destroy',
                'description' => NULL,
                'created_at' => '2020-02-19 08:56:42',
                'updated_at' => '2020-02-19 08:57:06',
                'parent_id' => 147,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            120 => 
            array (
                'id' => 167,
                'name' => 'ajax-get-models-by-brand-id-frontend',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2020-02-19 08:56:42',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 8,
                'icon' => NULL,
                'isURL' => 1,
            ),
            121 => 
            array (
                'id' => 168,
                'name' => 'compareByAjaxFrontend',
                'display_name' => NULL,
                'description' => NULL,
                'created_at' => '2020-02-19 08:56:42',
                'updated_at' => '2020-03-20 05:07:22',
                'parent_id' => 0,
                'order' => 9,
                'icon' => NULL,
                'isURL' => 1,
            ),
            122 => 
            array (
                'id' => 169,
                'name' => 'divisions.index',
                'display_name' => 'Index',
                'description' => NULL,
                'created_at' => '2020-02-20 07:02:14',
                'updated_at' => '2020-03-20 05:07:21',
                'parent_id' => 0,
                'order' => 7,
                'icon' => NULL,
                'isURL' => 1,
            ),
            123 => 
            array (
                'id' => 170,
                'name' => 'divisions.create',
                'display_name' => 'Create',
                'description' => NULL,
                'created_at' => '2020-02-20 07:02:15',
                'updated_at' => '2020-02-20 07:03:40',
                'parent_id' => 169,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            124 => 
            array (
                'id' => 171,
                'name' => 'divisions.store',
                'display_name' => 'Store',
                'description' => NULL,
                'created_at' => '2020-02-20 07:02:15',
                'updated_at' => '2020-02-20 07:03:41',
                'parent_id' => 169,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            125 => 
            array (
                'id' => 172,
                'name' => 'divisions.edit',
                'display_name' => 'Edit',
                'description' => NULL,
                'created_at' => '2020-02-20 07:02:15',
                'updated_at' => '2020-02-20 07:03:41',
                'parent_id' => 169,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            126 => 
            array (
                'id' => 173,
                'name' => 'divisions.update',
                'display_name' => 'Update',
                'description' => NULL,
                'created_at' => '2020-02-20 07:02:15',
                'updated_at' => '2020-02-20 07:03:41',
                'parent_id' => 169,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            127 => 
            array (
                'id' => 174,
                'name' => 'divisions.destroy',
                'display_name' => 'Destroy',
                'description' => NULL,
                'created_at' => '2020-02-20 07:02:15',
                'updated_at' => '2020-02-20 07:03:41',
                'parent_id' => 169,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            128 => 
            array (
                'id' => 176,
                'name' => '#DivisionSetup',
                'display_name' => 'Setup Division',
                'description' => NULL,
                'created_at' => '2020-02-20 08:04:13',
                'updated_at' => '2020-03-20 05:07:21',
                'parent_id' => 0,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 0,
            ),
            129 => 
            array (
                'id' => 177,
                'name' => 'sub-division.index',
                'display_name' => 'Index',
                'description' => NULL,
                'created_at' => '2020-02-20 09:15:37',
                'updated_at' => '2020-03-20 05:07:21',
                'parent_id' => 0,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            130 => 
            array (
                'id' => 178,
                'name' => 'sub-division.create',
                'display_name' => 'Create',
                'description' => NULL,
                'created_at' => '2020-02-20 09:15:37',
                'updated_at' => '2020-02-20 09:16:16',
                'parent_id' => 177,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            131 => 
            array (
                'id' => 179,
                'name' => 'sub-division.store',
                'display_name' => 'Store',
                'description' => NULL,
                'created_at' => '2020-02-20 09:15:37',
                'updated_at' => '2020-02-20 09:16:16',
                'parent_id' => 177,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            132 => 
            array (
                'id' => 180,
                'name' => 'sub-division.edit',
                'display_name' => 'Edit',
                'description' => NULL,
                'created_at' => '2020-02-20 09:15:37',
                'updated_at' => '2020-02-20 09:16:16',
                'parent_id' => 177,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            133 => 
            array (
                'id' => 181,
                'name' => 'sub-division.update',
                'display_name' => 'Update',
                'description' => NULL,
                'created_at' => '2020-02-20 09:15:37',
                'updated_at' => '2020-02-20 09:16:16',
                'parent_id' => 177,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            134 => 
            array (
                'id' => 182,
                'name' => 'sub-division.destroy',
                'display_name' => 'Destroy',
                'description' => NULL,
                'created_at' => '2020-02-20 09:15:37',
                'updated_at' => '2020-02-20 09:16:16',
                'parent_id' => 177,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            135 => 
            array (
                'id' => 183,
                'name' => 'attribute.index',
                'display_name' => 'Index',
                'description' => NULL,
                'created_at' => '2020-03-20 04:42:35',
                'updated_at' => '2020-03-20 05:07:21',
                'parent_id' => 0,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            136 => 
            array (
                'id' => 184,
                'name' => 'attribute.create',
                'display_name' => 'Create',
                'description' => NULL,
                'created_at' => '2020-03-20 04:42:35',
                'updated_at' => '2020-03-20 04:43:05',
                'parent_id' => 183,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            137 => 
            array (
                'id' => 185,
                'name' => 'attribute.store',
                'display_name' => 'Store',
                'description' => NULL,
                'created_at' => '2020-03-20 04:42:35',
                'updated_at' => '2020-03-20 04:43:06',
                'parent_id' => 183,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            138 => 
            array (
                'id' => 186,
                'name' => 'attribute.edit',
                'display_name' => 'Edit',
                'description' => NULL,
                'created_at' => '2020-03-20 04:42:35',
                'updated_at' => '2020-03-20 04:43:06',
                'parent_id' => 183,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            139 => 
            array (
                'id' => 187,
                'name' => 'attribute.update',
                'display_name' => 'Update',
                'description' => NULL,
                'created_at' => '2020-03-20 04:42:35',
                'updated_at' => '2020-03-20 04:43:06',
                'parent_id' => 183,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            140 => 
            array (
                'id' => 188,
                'name' => 'attribute.destroy',
                'display_name' => 'Destroy',
                'description' => NULL,
                'created_at' => '2020-03-20 04:42:35',
                'updated_at' => '2020-03-20 04:43:06',
                'parent_id' => 183,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
            141 => 
            array (
                'id' => 189,
                'name' => 'sub-attribute-index',
                'display_name' => 'Index',
                'description' => NULL,
                'created_at' => '2020-03-20 05:07:01',
                'updated_at' => '2020-03-20 05:07:23',
                'parent_id' => 0,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            142 => 
            array (
                'id' => 190,
                'name' => 'sub-attribute-create',
                'display_name' => 'Create',
                'description' => NULL,
                'created_at' => '2020-03-20 05:07:01',
                'updated_at' => '2020-03-20 05:07:23',
                'parent_id' => 189,
                'order' => 2,
                'icon' => NULL,
                'isURL' => 1,
            ),
            143 => 
            array (
                'id' => 191,
                'name' => 'sub-attribute-store',
                'display_name' => 'Store',
                'description' => NULL,
                'created_at' => '2020-03-20 05:07:01',
                'updated_at' => '2020-03-20 05:07:23',
                'parent_id' => 189,
                'order' => 3,
                'icon' => NULL,
                'isURL' => 1,
            ),
            144 => 
            array (
                'id' => 192,
                'name' => 'sub-attribute-edit',
                'display_name' => 'Edit',
                'description' => NULL,
                'created_at' => '2020-03-20 05:07:01',
                'updated_at' => '2020-03-20 05:07:23',
                'parent_id' => 189,
                'order' => 4,
                'icon' => NULL,
                'isURL' => 1,
            ),
            145 => 
            array (
                'id' => 193,
                'name' => 'sub-attribute-update',
                'display_name' => 'Update',
                'description' => NULL,
                'created_at' => '2020-03-20 05:07:01',
                'updated_at' => '2020-03-20 05:07:24',
                'parent_id' => 189,
                'order' => 5,
                'icon' => NULL,
                'isURL' => 1,
            ),
            146 => 
            array (
                'id' => 194,
                'name' => 'sub-attribute-destroy',
                'display_name' => 'Destroy',
                'description' => NULL,
                'created_at' => '2020-03-20 05:07:01',
                'updated_at' => '2020-03-20 05:07:24',
                'parent_id' => 189,
                'order' => 6,
                'icon' => NULL,
                'isURL' => 1,
            ),
        ));
        
        
    }
}